FROM rocker/rstudio:3.3.3

RUN R -e 'install.packages("devtools")'


RUN R -e 'library(devtools); \
          install_version("ggplot2", "2.2.1");'

RUN R -e 'library(devtools); \
          install_version("dplyr", "0.5.0");'

RUN R -e 'library(devtools); \
          install_version("tidyr", "0.6.1");'

RUN R -e 'library(devtools); \
          install_version("data.table", "1.10.4");'

RUN R -e 'library(devtools); \
          install_version("leaflet", "1.1.0");'

RUN R -e 'library(devtools); \
          install_version("shiny", "1.0.1", repos = "https://cloud.r-project.org/");'

RUN R -e 'library(devtools); \
          install_version("vcd", "1.4-3");'

RUN R -e 'library(devtools); \
          install_version("plotly", "4.5.2");'

RUN R -e 'library(devtools); \
          install_version("plyr", "1.8.4");'

RUN R -e 'library(devtools); \
          install_version("rmarkdown", "1.3");'

RUN R -e 'library(devtools); \
          install_version("forecast", "8.0");'

RUN R -e 'library(devtools); \
          install_version("RSQLite", "1.1-2");'

RUN R -e 'library(devtools); \
          install_version("reshape2", "1.4.2");'

RUN R -e 'library(devtools); \
          install_version("nycflights13", "0.2.2");'

RUN R -e 'library(devtools); \
          install_version("caret", "6.0-73");'

RUN R -e 'library(devtools); \
          install_version("RCurl", "1.95-4.8");'

RUN R -e 'library(devtools); \
          install_version("crayon", "1.3.2");'

RUN R -e 'library(devtools); \
          install_version("psych", "1.7.3.21");'

RUN R -e 'library(devtools); \
          install_version("igraph", "1.0.1");'

RUN R -e 'library(devtools); \
          install_version("NLP", "0.1-10");'

RUN R -e 'library(devtools); \
          install_version("tm", "0.7-1");'

RUN R -e 'library(devtools); \
          install_version("magrittr", "1.5");'

RUN R -e 'library(devtools); \
          install_version("quanteda", "0.9.9-24");'

RUN R -e 'library(devtools); \
          install_version("stringr", "1.2.0");'

RUN R -e 'library(devtools); \
          install_version("shinydashboard", "0.5.3");'

RUN R -e 'library(devtools); \
          install_version("SnowballC", "0.5.1");'

RUN R -e 'library(devtools); \
          install_version("DT", "0.2");'

RUN R -e 'library(devtools); \
          install_version("RColorBrewer", "1.1-2");'

RUN R -e 'library(devtools); \
          install_version("broom", "0.4.2");'

RUN R -e 'library(devtools); \
          install_version("MASS", "7.3-45");'

RUN R -e 'library(devtools); \
          install_version("randomForest", "4.6-12");'

RUN R -e 'library(devtools); \
          install_version("wordcloud", "2.5");'

RUN R -e 'library(devtools); \
          install_version("likert", "1.3.5");'

RUN echo 'deb http://ftp.ca.debian.org/debian unstable main' >> /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y libxml2-dev

RUN R -e 'library(devtools); \
          install_version("tidyverse", "1.1.1");'

RUN R -e 'library(devtools); \
          install_github("exploratory-io/exploratory_func");'

RUN R -e 'library(devtools); \
          install_version("corrplot", "0.77");'

RUN R -e 'library(devtools); \
          install_version("ggdendro", "0.1-20");'

RUN R -e 'library(devtools); \
          install_version("spatstat", "1.50-0");'

RUN R -e 'library(devtools); \
          install_version("visNetwork", "1.0.3");'

RUN R -e 'library(devtools); \
          install_version("googleVis", "0.6.2");'

RUN R -e 'library(devtools); \
          install_version("topicmodels", "0.2-5");'

RUN R -e 'library(devtools); \
          install_version("LDAvis", "0.3.2");'

RUN R -e 'library(devtools); \
          install_version("fields", "8.10");'
